# Generated by Django 5.1.6 on 2025-05-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(choices=[('books', 'Книги'), ('electronics', 'Электроника'), ('clothes', 'Одежда'), ('transport', 'Транспорт'), ('furniture', 'Мебель')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_images/'),
        ),
    ]
